image: sknnr/icarus-dedicated-server
imageTag: latest
# serviceType should be LoadBalancer or NodePort
serviceType: LoadBalancer
resources:
  requests:
    memory: 16G
    cpu: 8.0
volumes:
  dataPVC:
    size: 50Gi
  storageClassName: ""
env:
  serverName: Icarus Kubernetes Server
  gamePort: 17777
  queryPort: 27015
  joinPassword: changeme
  maxPlayers: 8
  adminPassword: adminchangeme
  shutdownNotJoinedFor: -1
  shutdownEmptyFor: -1
  allowNonAdminsLaunch: True
  allowNonAdminsDelete: False
  loadProspect: False
  createProspect: False
  resumeProspect: True
  steamAsyncTimeout: 120
